registry:
    # Docker registry url
    url: http://registry-srv:5000/v2
    # Docker registry fqdn
    name: localhost:5000
    # To allow image delete, should be false
    readonly: false
    # trust_any_ssl 에서 ssl 무시하고 싶다면 true (default: false)
    # trust_any_ssl: false
    auth:
        # Enable authentication
        enabled: true
        # Token issuer
        # should equals to auth.token.issuer of docker registry
        issuer: 'my issuer'
        # Private key for token signing
        # certificate used on auth.token.rootcertbundle should signed by this key
        key: /conf/auth.key
