version: '3'
services:
    registry-web:
        image: hyper/docker-registry-web:latest
        container_name: registry-web
        ports:
            - 8080:8080
        volumes:
            - ./conf/registry-web:/conf:ro
            # - ./db:/data
        networks:
            - registry-net
        depends_on:
            - registry
    registry:
        image: registry:2
        container_name: registry-srv
        ports:
            - 5000:5000
        volumes:
            - ./conf/registry:/etc/docker/registry:ro
            # - ./registry:/var/lib/registry
        networks:
            - registry-net

networks:
    registry-net:
