version: 0.1

storage:
    filesystem:
        rootdirectory: /var/lib/registry
    delete:
        enabled: true

http:
    addr: 0.0.0.0:5000

auth:
    token:
        # external url to docker-web authentication endpoint
        realm: http://localhost:8080/api/auth

        # ex) 배포 서버 주소가 123.123.123.123 일 경우 이걸로 변경
        #realm: http://123.123.123.123:8080/api/auth

        # should be same as registry.name of registry-web
        service: localhost:5000
        # should be same as registry.auth.issuer of registry-web
        issuer: 'my issuer'
        # path to auth certificate
        rootcertbundle: /etc/docker/registry/auth.cert

log:
    level: info

notifications:
    endpoints:
        - name: listener
          url: http://registry-web:8080/api/notification
          timeout: 500ms
          threshold: 5
          backoff: 1s
