name: CI Pipeline
on:
    push:
        branches:
            - master
jobs:
    build-and-test:
        runs-on: ubuntu-latest # 테스트할 리눅스,
        steps:
            - name: docker push
              run: |
                  # github docker 셋팅 
                  echo '{"insecure-registries": ["3.39.6.193:5000", "3.39.6.193:8080"]}' | sudo tee /etc/docker/daemon.json
                  sudo systemctl restart docker

                  docker login 3.39.6.193:5000 -u admin -p 1q2w3e4r
                  # docker pull nginx
                  # docker tag nginx 3.39.6.193:5000/nginx:latest
                  docker pull 3.39.6.193:5000/nginx:latest
                  docker images
